version: '3.8'

services:
  linear-rag:
    build:
      context: .
      dockerfile: Dockerfile
    image: linear-rag:latest
    container_name: linearrag-service
    volumes:
      # 【关键：宿主机路径:容器路径】
      # 挂载
      - /home/dev/huangbinghan/LinearRAG-main/.venv/lib/python3.12/site-packages:/app/.venv/lib/python3.12/site-packages:ro

    # 对应 --network host
    # 注意：使用 host 模式后，ports 映射会被忽略，容器直接使用 12124 端口
    network_mode: "host"
    
    # 对应 --restart always
    restart: always
    
    # 对应 --gpus all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    # 环境变量配置
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
      - SW_AGENT_NAME=linearrag-service
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=192.168.102.22:11807
      - SW_AGENT_PROTOCOL=grpc
      - SW_AGENT_LOGGING_LEVEL=INFO
      - LLM_API_KEY=sk
      - LLM_BASE_URL=http://192.168.102.19:8082/v1
      - LLM_MODEL_NAME=qwen3
      - EMBEDDING_API_URL=http://192.168.102.19:8082/v1/embeddings
      - EMBEDDING_MODEL_NAME=qwen3-embedding
      - SPACY_MODEL=zh_core_web_md
      - MAX_WORKERS=16
