[project]
name = "linearrag-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elasticsearch==8.14.0",
    "fastapi>=0.127.0",
    "langchain==0.3.21",
    "langchain-elasticsearch==0.3.0",
    "loguru>=0.7.3",
    "neo4j>=6.0.3",
    "pipreqs>=0.5.0",
    "uvicorn>=0.40.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
